version: '2'
services:
    lab3:
        container_name: "progetto"
        image: r4ffy/progetto
        ports:
            - 8080:8080
        links:
            - db
        depends_on:
            - db
    db:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
